name: "Rebuild Site"
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  site:
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-site.yaml@main
    with:
      owner: '${{ github.event.repository.owner.login }}'
      name: '${{ github.event.repository.name }}'
      slug: '${{ github.event.repository.owner.login }}'
      email: '${{ github.event.repository.owner.id }}+${{ github.event.repository.owner.login }}@users.noreply.github.com'
    secrets:
      id: 'none'
      key: ${{ secrets.GITHUB_TOKEN }}
